[matching]
'.sublime-music-wrapped' = ''
'Chromium-browser' = ''
'Electron' = ''
'Element' = ''
'com.obsproject.Studio' = ''
'emacs' = ''
'Emacs' = ''
'firefox' = ''
'mpv' = ''
'Sonixd' = ''