[matching]
'.sublime-music-wrapped' = ''
'Chromium-browser' = ''
'Electron' = ''
'Element' = ''
'com.obsproject.Studio' = ''
'emacs' = ''
'Emacs' = ''
'firefox' = ''
'firefox-esr' = ''
'godot' = ''
'Godot' = ''
'mpv' = ''
'foobar' = ''
'org.remmina.Remmina' = ''
'Sonixd' = ''
'steam' = ''
'thunar' = ''
'Vivaldi-stable' = ''