{ pkgs, ... }:
pkgs.emacsWithPackagesFromUsePackage {
  config = "";
  package = pkgs.emacsPgtkGcc;
  alwaysEnsure = true;
  override = epkgs: epkgs // {
    telega = epkgs.melpaPackages.telega;
  };
  extraEmacsPackages = epkgs: with epkgs; [
    ace-window
    adaptive-wrap
    ag
    aggressive-indent
    anzu
    beacon
    biblio
    bibtex-completion
    company
    consult
    consult-projectile
    dante
    diff-hl
    diminish
    direnv
    doom-themes
    drag-stuff
    editorconfig
    eglot
    elfeed
    elfeed-org
    emacsql
    emacsql-sqlite3
    eslint-fix
    forge
    flycheck
    flycheck-rust
    fullframe
    git-link
    git-timemachine
    golden-ratio
    haskell-mode
    hcl-mode
    helpful
    highlight-indent-guides
    htmlize
    ivy
    ivy-bibtex
    js2-mode
    json-mode
    ledger-mode
    lsp-mode
    lsp-ui
    magit
    marginalia
    markdown-mode
    nix-mode
    no-littering
    orderless
    org
    org-contrib
    org-randomnote
    org-ref
    org-roam
    org-roam-bibtex
    org-superstar
    ox-hugo
    pdf-tools
    popper
    projectile
    rainbow-delimiters
    ripgrep
    ron-mode
    rust-mode
    selectrum
    selectrum-prescient
    shackle
    smartparens
    spinner
    telega
    templatel
    tide
    toml-mode
    treemacs
    treemacs-magit
    treemacs-projectile
    use-package
    vertico
    visual-fill-column
    vterm
    web-mode
    weblorg
    webpaste
    which-key
    with-editor
    writeroom-mode
    ws-butler
    yaml-mode
    yasnippet
    zenburn-theme
  ];
}
